spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=false

spring.cloud.config.enabled=false

aws.accessKey=AKIAQBLBVTAWWGT7Z6O7
aws.secretKey=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
aws.region=eu-north-1
aws.bucketName=recruitment-syste-files

cloudinary.cloud_name=mcloud-server
cloudinary.api_key=573627528259572
cloudinary.api_secret=fmGxkIy5ad3H5SHM9pwLIqxb9UQ

jwt.secret=U2VjdXJlSldUU2VjcmV0S2V5MTIzNDU2Nzg5MDEyMzQ1Njc4OTA

server.port=8000
server.address=0.0.0.0