spring.cloud.config.enabled=false
server.host=localhost:8000
server.port=8000
server.address=0.0.0.0

jwt.secret=U2VjdXJlSldUU2VjcmV0S2V5MTIzNDU2Nzg5MDEyMzQ1Njc4OTA=

# Supabase PostgreSQL via Connection Pooler
spring.datasource.url=jdbc:postgresql://aws-1-eu-north-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.denmjcucrxmfrsouyppw
spring.datasource.password=F7!qZ$9mL@2r#V8x
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.hikari.data-source-properties.prepareThreshold=0
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
spring.jpa.properties.hibernate.use_sql_comments=true


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

cloudinary.cloud_name=mcloud-server
cloudinary.api_key=573627528259572
cloudinary.api_secret=fmGxkIy5ad3H5SHM9pwLIqxb9UQ

spring.web.error.include-message=always
logging.level.org.springframework=DEBUG