spring.cloud.config.enabled=false

server.port=${PORT:8000}
server.address=0.0.0.0

jwt.secret=${JWT_SECRET}

# Supabase PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_FORMAT_SQL:true}
spring.datasource.hikari.data-source-properties.prepareThreshold=0
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
spring.jpa.properties.hibernate.use_sql_comments=${SPRING_JPA_USE_SQL_COMMENTS:true}

# File upload
spring.servlet.multipart.max-file-size=${MULTIPART_MAX_FILE_SIZE:10MB}
spring.servlet.multipart.max-request-size=${MULTIPART_MAX_REQUEST_SIZE:10MB}

# Cloudinary
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

# Error handling and logging
spring.web.error.include-message=${SPRING_WEB_ERROR_INCLUDE_MESSAGE:always}
logging.level.org.springframework=${SPRING_LOG_LEVEL:INFO}
logging.level.software.amazon.awssdk=${AWS_SDK_LOG_LEVEL:INFO}

# AWS S3
aws.accessKey=${AWS_ACCESS_KEY}
aws.secretKey=${AWS_SECRET_KEY}
aws.region=${AWS_REGION}
aws.bucketName=${AWS_S3_BUCKET}
#spring.profiles.active=dev